### ISSUE TITLE
Not working with minitest 5

### ISSUE THREAD

**Issue by NicolasWebDev** [jnbt/minitest-growl#2]
Gives the following error:
```
/home/sathors/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-growl-0.0.3/lib/minitest/growl_notify.rb:40:in `<top (required)>': undefined method `output' for Minitest::Unit:Class (NoMethodError)        
        from test/sri_test.rb:3:in `require'        
        from test/sri_test.rb:3:in `<main>'         
```

Related to torquebox/jruby-maven-plugins#74.

Seems that Minitest::Unit.output has been removed in minitest 5.

**Comment by jnbt** [comment]
@NicolasWebDev Hi, thanks for this feedback.

In fact Minitest has changed the way to integrate reporters. I've published a new version which adopts the new MiniTest plugin architecture and gets rid of the `growlnotify` binary dependency.

Please update to `0.1.0` which will use the `ruby-growl` gem to push notifications to Growl.

**Comment by NicolasWebDev** [comment]
Hi @jnbt, thanks a lot for your reactivity!
